services:
  slides:
    image: ${SLIDES_IMAGE}
    ports:
      - "23234:23234"
    volumes:
      - ./slides:/app
  proxy:
    image: ${PROXY_IMAGE}
    ports:
      - "${PROXY_SSH_PORT}:2222"
    volumes:
      - ./proxy:/workspace
    environment:
      - TARGET_HOST=slides
      - TARGET_PORT=23234
      - LANG=C.UTF-8
      - TERM=xterm-256color
      - SSH_HOST_KEY=/workspace/ssh_host_key
      - STRICT=${STRICT}
      - SSH_TRUSTED_USERS_CA=${SSH_TRUSTED_USERS_CA}
    