on:
  push:
    branches: [develop, main]
    tags: ["v*"]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  ECR_REGISTRY: 160927904376.dkr.ecr.eu-west-3.amazonaws.com
  AWS_REGION: eu-west-3
  ARTEFACTS_S3_BUCKET: tfartefacts-zshowcase-eu-west-3
  CHANNEL: ${{ startsWith(github.ref, 'refs/tags/v') && 'prod' || (github.ref == 'refs/heads/main' && 'staging') || 'dev' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/tags/v') && 'prod' || (github.ref == 'refs/heads/main' && 'staging') || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Determine base commit
        id: base
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          TAG="${GITHUB_REF#refs/tags/}"

          if [[ "$GITHUB_REF" == refs/heads/develop ]]; then
            # Develop → commit précédent
            echo "base=${GITHUB_EVENT_BEFORE}" >> $GITHUB_OUTPUT

          elif [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            # Main → push d’un tag v*
            # On récupère les tags existants triés par date décroissante
            LAST_TAG=$(git tag --list "v*" --sort=-creatordate | sed -n '2p')

            if [[ -n "$LAST_TAG" ]]; then
              # S'il existe un tag précédent → on prend ce tag
              BASE=$(git rev-list -n 1 "$LAST_TAG")
              echo "base=$BASE" >> $GITHUB_OUTPUT
            else
              # Pas de tag précédent → on prend le commit précédent du tag
              echo "base=${GITHUB_EVENT_BEFORE}" >> $GITHUB_OUTPUT
            fi

          elif [[ "$GITHUB_REF" == refs/heads/main ]]; then
            # Main normal → commit précédent
            echo "base=${GITHUB_EVENT_BEFORE}" >> $GITHUB_OUTPUT
          fi
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: ${{ steps.base.outputs.base }}
          filters: |
            docker:
              - 'proxy/**'
              - 'slides/**'

            content:
              - 'content/**'

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          audience: sts.amazonaws.com
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{vars.AWS_ROLE_ARN}}

      - name: Build & push Docker image
        if: steps.changes.outputs.docker == 'true'
        shell: bash
        run: |
          set -euo pipefail
          ./scripts/build_push.sh $CHANNEL

      - name: Update slides content
        if: steps.changes.outputs.content == 'true'
        shell: bash
        run: |
          set -euo pipefail
          ./scripts/upload_slides_content.sh

      - name: Deploy via AWS SSM
        if: steps.changes.outputs.docker == 'true' || steps.changes.outputs.content == 'true'
        shell: bash
        run: |
          set -euo pipefail
          ./scripts/deploy_ssm.sh $CHANNEL