on:
  push:
    branches: [develop, main]
    tags: ["v*"]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  ECR_REGISTRY: 160927904376.dkr.ecr.eu-west-3.amazonaws.com
  AWS_REGION: eu-west-3
  ARTEFACTS_S3_BUCKET: tfartefacts-zshowcase-eu-west-3
  CHANNEL: ${{ startsWith(github.ref, 'refs/tags/v') && 'prod' || (github.ref == 'refs/heads/main' && 'staging') || 'dev' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/tags/v') && 'prod' || (github.ref == 'refs/heads/main' && 'staging') || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          audience: sts.amazonaws.com
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{vars.AWS_ROLE_ARN}}

      - name: Build & push Docker image
        shell: bash
        run: |
          set -euo pipefail
          ./scripts/build_push.sh $CHANNEL

      - name: Update slides content
        shell: bash
        run: |
          set -euo pipefail
          ./scripts/upload_slides_content.sh

      - name: Deploy via AWS SSM
        shell: bash
        run: |
          set -euo pipefail
          ./scripts/deploy_ssm.sh $CHANNEL